version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: h4ck3rs_4_l1f3
      POSTGRES_DB: bookingdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./booking_system_structure.sql:/docker-entrypoint-initdb.d/booking_system_structure.sql

volumes:
  db_data:
