POST http://localhost:5000/api/register HTTP/1.1
content-type: application/json

{
    "username": "ch",
    "email" : "chris5@gmail.com",
    "password": "test1234"
}

###
GEt http://localhost:5000/api/register HTTP/1.1

###
POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
    "email" : "chrimail.com",
    "password": "test1234"
}

###
GET http://192.168.2.122:5173/login HTTP/1.1
content-type: application/json

{
    "email" : "chrimail.com",
    "password": "test1234"
}